version: '3.4'

services:
  zaliczenie:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - /mnt/c/Users/JS/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
